<a href="https://colab.research.google.com/github/JuanCappelletti/Consteel_H06/blob/trends/caidas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
#@title Ejecutar librerias { run: "auto", display-mode: "form" }
from matplotlib.font_manager import json_dump
from numpy.matrixlib.defmatrix import N
from operator import truediv
import numpy as np
import pandas as pd
from matplotlib.ticker import (MultipleLocator, AutoMinorLocator)
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from IPython.display import Image

#Carga de tablas_______________
Url = "https://raw.githubusercontent.com/JuanCappelletti/Consteel_H06/main/sagomario.csv"
Sagomario = pd.read_csv(Url,sep=";",decimal=",")


In [ ]:
#Sagomario


In [61]:
from pickle import TRUE
#@title Carga general de datos
Qteorico=np.array(np.linspace(1, 18000, 3600, endpoint=True,dtype=int)) #Nm3/h
Temp_celsius = 25 #@param {type:"integer"}
Altitud_m = 20 #@param {type:"number"}
atm_local=(1-0.00002257*Altitud_m)**5.256
#@markdown Indicar valor de presion de partida (tildar unidad de ingreso)
Barg = True #@param {type:"boolean"}
Kgcm2 = False #@param {type:"boolean"}
Pressure_in = 15 #@param {type:"number"}
Temp=(Temp_celsius+273.15)/273.15 #temperatura en kelvin

if Barg==True and Kgcm2== False:
   Pressure_op= Pressure_in*0.986923 #atm
elif Barg==False and Kgcm2== True:
   Pressure_op= Pressure_in*0.967841 # atm
else :
   print('Mensaje ERROR: Se requiere opción de unidad , Tildar solo una')

#print(atm_local)
#print(Temp*273.15)
#print(Temp)
Qnormalizado=np.round(Qteorico*(Temp*(1/(atm_local+Pressure_op))),decimals=2)




array([7.00000e-02, 4.10000e-01, 7.60000e-01, ..., 1.24263e+03,
       1.24298e+03, 1.24339e+03])

In [2]:
#@title Tramo 1


Qteorico=np.linspace(1, 18000, 3600, endpoint=True,dtype=int) #Nm3/h
Qnormalizado=Qteorico

##datos = pd.read_csv(Url,sep=";",decimal=",")
##df=pd.DataFrame(datos)
#dfx=df.copy()
Qteorico


array([    1,     6,    11, ..., 17989, 17994, 18000])

In [ ]:
def velocidad(Caudal):
  Velocity=Caudal/1000
  print(Velocity)

In [ ]:
velocidad(Qteorico)



[1.0000e-03 6.0000e-03 1.1000e-02 ... 1.7989e+01 1.7994e+01 1.8000e+01]
